# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [3]:
import numpy as np


2. Create a null vector of size 10 

In [5]:
vector=np.zeros(10)
vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [6]:
arr1 = np.arange(10,49)


4. Find the shape of previous array in question 3)

In [7]:
np.shape(arr1)

(39,)

5. Print the type of the previous array in question 3

In [8]:
arr1.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [9]:
import numpy
print(np.__version__)
numpy.show_config()

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/um964/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/um964/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/um964/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/um964/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/um964/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/um964/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/um964/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/um964/Anaconda3\\Library\\include']


7. Print the dimension of the array in question 3


In [19]:
arr1.ndim

1

8. Create a boolean array with all the True values

In [24]:
arr1 >9

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

9. Create a two dimensional array




In [37]:
arr2 = np.array(range(10))
arr2.reshape(2,5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

10. Create a three dimensional array



In [40]:
arr3 = np.array(range(30))
arr3.reshape(3,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [43]:
arr4 = [1,2,3,4,5,6,7,8,9,10]
arr4 = arr4[::-1]
arr4

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

12. Create a null vector of size 10 but the fifth value which is 1 

In [49]:
vector=np.zeros(10)
vector[4] = 1
vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [10]:
array=np.identity(3)
array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [59]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype(float)
arr.dtype

dtype('float64')

15. arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])  arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

---


Multiply arr1 with arr2


In [12]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
a=np.multiply(arr1,arr2)
a

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [25]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2[arr2>arr1]

array([ 4.,  7., 12.])

17. Extract all odd numbers from arr with values(0-9)

In [16]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[1::2]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [21]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[1] = 0
arr[3] = 0
arr[4] = 0
arr[7] = 0
arr[9] = 0
arr

array([0, 0, 2, 0, 0, 5, 6, 0, 8, 0])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [23]:
arr = np.arange(10)
arr[5] = 12
arr[6] = 12
arr[7] = 12
arr[8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [68]:
arr2d = np.array ([[1,0,0,0,1], [1,0,0,0,1]])
arr2d


array([[1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

---

Replace the value 5 to 12

In [72]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[1,1] =12
arr2d[1,1]

12

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [74]:
arr = np.array([[0,1,2,3,4], [5,6,7,8,9]])
arr[0, 0:]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [76]:
arr = np.array([[0,1,2,3,4], [5,6,7,8,9]])
arr[1,1:2]


array([6])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

26. Create a 10x10 array with random values and find the minimum and maximum values

In [28]:
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.77497948 0.63596551 0.32012687 0.83516809 0.61196011 0.45614464
  0.27996843 0.7757643  0.21548212 0.93284509]
 [0.9647814  0.69758269 0.06341574 0.27418546 0.62010525 0.47201137
  0.70093339 0.73055807 0.33772479 0.25215149]
 [0.86944101 0.78505702 0.13180202 0.64898092 0.35564192 0.45004187
  0.84548604 0.72142023 0.95320506 0.47800164]
 [0.88487652 0.46073015 0.41490239 0.36324687 0.54270117 0.44488453
  0.19145792 0.21950841 0.6007608  0.04122411]
 [0.72755335 0.17121492 0.13745167 0.29434683 0.29840674 0.19730755
  0.66671165 0.87368407 0.04576194 0.43947228]
 [0.316004   0.55595238 0.78095939 0.54823449 0.95768082 0.28881864
  0.16641404 0.11205207 0.52731764 0.45886969]
 [0.53934106 0.32254517 0.45177162 0.95198909 0.55422903 0.5926106
  0.98932005 0.18095091 0.98786485 0.41295945]
 [0.56731198 0.5877066  0.29321976 0.26885397 0.485108   0.11413302
  0.1042354  0.14434471 0.18758371 0.70672951]
 [0.90372399 0.52929983 0.3593395  0.34249344 0.16778132 0.136830

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [93]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)


array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [94]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [79]:
arr2d = np.array ([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [87]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
arr4 = arr3.reshape(2,2,4)
arr4

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [92]:
arr4.swapaxes(1,2).shape

(2, 4, 2)

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [29]:
arr = np.array([0.1,16,9,25,81,64, 121, 169, 400, 2500])
a= np.sqrt(arr)
print(a)
a[a < .5] = 0
print(a)

[ 0.31622777  4.          3.          5.          9.          8.
 11.         13.         20.         50.        ]
[ 0.  4.  3.  5.  9.  8. 11. 13. 20. 50.]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [38]:
arr1 = np.random.random(12)
arr2 = np.random.random(12)
arr3

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [39]:
a = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
[a[i] for i in sorted(np.unique(a, return_index=True)[1])]

['Bob', 'Joe', 'Will']

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [48]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
result = np.setdiff1d(a, b)
result

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [41]:
a = numpy.array([[34,43,73],[82,22,12],[53,94,66]])


np.delete(a, 1,0 )

array([[34, 43, 73],
       [53, 94, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [42]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [46]:
x = np.random.random((20))
a= np.cumsum(x)
a

array([0.99703037, 1.35707908, 1.85090699, 2.26962576, 2.59724752,
       2.95711886, 3.1467017 , 3.21996318, 3.23904308, 3.43315251,
       4.00569829, 4.9163578 , 5.23592089, 6.06080216, 6.65060969,
       6.7882521 , 7.0579781 , 7.17671739, 7.38921634, 7.80313953])